

package chatserver;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import java.util.Vector;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Riby
 */
public class ServerHandler extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public static Map<Integer, Boolean> PORT = new HashMap<Integer, Boolean>();
    public static HashSet<clientGUI> CLIENTS=new HashSet();
        ExecutorService executor = Executors.newFixedThreadPool(30);
            
    public static final int MAX_PORT = 10;
    public static int s = 12345;

    public static String USER = "default";
     public static Thread[] Y = new Thread[30];
     public static int counter=0;

    public ServerHandler(String USER) {

        initComponents();
        ServerDBConnect ser = new ServerDBConnect();
        PORT=ser.getServerList();
        
        System.out.println(PORT);
        this.USER = USER;
        L_UserTitle.setText(USER + "'s Messenger");
     
        Fillcombo();
    }

    private void getServerListStatus() throws FileNotFoundException {
    
            ServerDBConnect ser = new ServerDBConnect();
        PORT=ser.getServerList();
    
        System.out.println(PORT);
    }

    private void Fillcombo() {
      
        available_chatServers.removeAllItems();
        Set<Integer> key = PORT.keySet();

        try {
            for (Integer k : key) {

                if (!PORT.get(k)) {

                    available_chatServers.addItem(k.toString());
                }
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_createServer = new javax.swing.JButton();
        B_JoinChat = new javax.swing.JButton();
        available_chatServers = new javax.swing.JComboBox();
        L_availbleServerList = new javax.swing.JLabel();
        L_UserTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_createServer.setText("Create Chat Server");
        B_createServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_createServerActionPerformed(evt);
            }
        });

        B_JoinChat.setText("Join Chat");
        B_JoinChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_JoinChatActionPerformed(evt);
            }
        });

        available_chatServers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available_chatServersActionPerformed(evt);
            }
        });

        L_availbleServerList.setText("Available Servers");

        L_UserTitle.setText("User Name'chatbox");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(B_createServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(available_chatServers, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_availbleServerList)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_UserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_JoinChat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(L_UserTitle)
                .addGap(86, 86, 86)
                .addComponent(L_availbleServerList)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_createServer)
                    .addComponent(available_chatServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_JoinChat)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_createServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_createServerActionPerformed

        chatServerA ch = null;
        Thread x = null;
        int port = 0;
        try {
            port = getFreePort();
        } catch (SQLException ex) {
            Logger.getLogger(ServerHandler.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Port" + port);

        ch = new chatServerA(port);
        x = new Thread(ch);
        x.start();

        Fillcombo();

    }//GEN-LAST:event_B_createServerActionPerformed

    private void B_JoinChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_JoinChatActionPerformed
        // TODO add your handling code here:
      
          synchronized(this){
    
        clientGUI c1 = new clientGUI(Integer.parseInt(available_chatServers.getSelectedItem().toString()),USER);
        
        Y[counter] = new Thread(c1);
        Y[counter++].start();
          }
    }//GEN-LAST:event_B_JoinChatActionPerformed

    private void available_chatServersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available_chatServersActionPerformed

        available_chatServers.setToolTipText("");
// TODO add your handling code here:
    }//GEN-LAST:event_available_chatServersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerHandler(USER).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_JoinChat;
    private javax.swing.JButton B_createServer;
    private javax.swing.JLabel L_UserTitle;
    private javax.swing.JLabel L_availbleServerList;
    private javax.swing.JComboBox available_chatServers;
    // End of variables declaration//GEN-END:variables

    
    //public 
    public int getFreePort() throws SQLException {
        
        
        Set<Integer> key = PORT.keySet();
        for (Integer k : key) {
            if (PORT.get(k)) {
                ServerDBConnect sDb=new ServerDBConnect();
                PORT.put(k, Boolean.FALSE);
                sDb.updateServerStatus(k,0);
                return k;
            }
        }
        //return 0 if no port is available
        return 0;

    }

}
